version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: dunya_user
      POSTGRES_PASSWORD: dunya_pass
      POSTGRES_DB: dunya_futbolu
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
