/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as TransferlerRouteImport } from './routes/transferler'
import { Route as ElaqeRouteImport } from './routes/elaqe'
import { Route as AxtarisRouteImport } from './routes/axtaris'
import { Route as IndexRouteImport } from './routes/index'
import { Route as XeberlerIndexRouteImport } from './routes/xeberler/index'
import { Route as KateqoriyaSlugRouteImport } from './routes/kateqoriya.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ArticleRouteImport } from './routes/article.'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferlerRoute = TransferlerRouteImport.update({
  id: '/transferler',
  path: '/transferler',
  getParentRoute: () => rootRouteImport,
} as any)
const ElaqeRoute = ElaqeRouteImport.update({
  id: '/elaqe',
  path: '/elaqe',
  getParentRoute: () => rootRouteImport,
} as any)
const AxtarisRoute = AxtarisRouteImport.update({
  id: '/axtaris',
  path: '/axtaris',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const XeberlerIndexRoute = XeberlerIndexRouteImport.update({
  id: '/xeberler/',
  path: '/xeberler/',
  getParentRoute: () => rootRouteImport,
} as any)
const KateqoriyaSlugRoute = KateqoriyaSlugRouteImport.update({
  id: '/kateqoriya/$slug',
  path: '/kateqoriya/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleRoute = ArticleRouteImport.update({
  id: '/article/',
  path: '/article/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/axtaris': typeof AxtarisRoute
  '/elaqe': typeof ElaqeRoute
  '/transferler': typeof TransferlerRoute
  '/video': typeof VideoRoute
  '/article/': typeof ArticleRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/kateqoriya/$slug': typeof KateqoriyaSlugRoute
  '/xeberler/': typeof XeberlerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/axtaris': typeof AxtarisRoute
  '/elaqe': typeof ElaqeRoute
  '/transferler': typeof TransferlerRoute
  '/video': typeof VideoRoute
  '/article': typeof ArticleRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/kateqoriya/$slug': typeof KateqoriyaSlugRoute
  '/xeberler': typeof XeberlerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/axtaris': typeof AxtarisRoute
  '/elaqe': typeof ElaqeRoute
  '/transferler': typeof TransferlerRoute
  '/video': typeof VideoRoute
  '/article/': typeof ArticleRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/kateqoriya/$slug': typeof KateqoriyaSlugRoute
  '/xeberler/': typeof XeberlerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/axtaris'
    | '/elaqe'
    | '/transferler'
    | '/video'
    | '/article/'
    | '/article/$slug'
    | '/kateqoriya/$slug'
    | '/xeberler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/axtaris'
    | '/elaqe'
    | '/transferler'
    | '/video'
    | '/article'
    | '/article/$slug'
    | '/kateqoriya/$slug'
    | '/xeberler'
  id:
    | '__root__'
    | '/'
    | '/axtaris'
    | '/elaqe'
    | '/transferler'
    | '/video'
    | '/article/'
    | '/article/$slug'
    | '/kateqoriya/$slug'
    | '/xeberler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AxtarisRoute: typeof AxtarisRoute
  ElaqeRoute: typeof ElaqeRoute
  TransferlerRoute: typeof TransferlerRoute
  VideoRoute: typeof VideoRoute
  ArticleRoute: typeof ArticleRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  KateqoriyaSlugRoute: typeof KateqoriyaSlugRoute
  XeberlerIndexRoute: typeof XeberlerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferler': {
      id: '/transferler'
      path: '/transferler'
      fullPath: '/transferler'
      preLoaderRoute: typeof TransferlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elaqe': {
      id: '/elaqe'
      path: '/elaqe'
      fullPath: '/elaqe'
      preLoaderRoute: typeof ElaqeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/axtaris': {
      id: '/axtaris'
      path: '/axtaris'
      fullPath: '/axtaris'
      preLoaderRoute: typeof AxtarisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xeberler/': {
      id: '/xeberler/'
      path: '/xeberler'
      fullPath: '/xeberler/'
      preLoaderRoute: typeof XeberlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kateqoriya/$slug': {
      id: '/kateqoriya/$slug'
      path: '/kateqoriya/$slug'
      fullPath: '/kateqoriya/$slug'
      preLoaderRoute: typeof KateqoriyaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/': {
      id: '/article/'
      path: '/article'
      fullPath: '/article/'
      preLoaderRoute: typeof ArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AxtarisRoute: AxtarisRoute,
  ElaqeRoute: ElaqeRoute,
  TransferlerRoute: TransferlerRoute,
  VideoRoute: VideoRoute,
  ArticleRoute: ArticleRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  KateqoriyaSlugRoute: KateqoriyaSlugRoute,
  XeberlerIndexRoute: XeberlerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
