/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as TransferlerRouteImport } from './routes/transferler'
import { Route as ElaqeRouteImport } from './routes/elaqe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as XeberlerIndexRouteImport } from './routes/xeberler/index'
import { Route as OlkeFutboluIndexRouteImport } from './routes/olke-futbolu/index'
import { Route as DunyaFutboluIndexRouteImport } from './routes/dunya-futbolu/index'
import { Route as OlkeFutboluPremyerLiqaRouteImport } from './routes/olke-futbolu/premyer-liqa'
import { Route as OlkeFutboluMilliKomandaRouteImport } from './routes/olke-futbolu/milli-komanda'
import { Route as OlkeFutboluILiqaRouteImport } from './routes/olke-futbolu/i-liqa'
import { Route as OlkeFutboluAzerbaycanKubokuRouteImport } from './routes/olke-futbolu/azerbaycan-kuboku'
import { Route as DunyaFutboluItaliyaRouteImport } from './routes/dunya-futbolu/italiya'
import { Route as DunyaFutboluIspaniyaRouteImport } from './routes/dunya-futbolu/ispaniya'
import { Route as DunyaFutboluIngiltereRouteImport } from './routes/dunya-futbolu/ingiltere'
import { Route as DunyaFutboluChempionlarLiqasiRouteImport } from './routes/dunya-futbolu/chempionlar-liqasi'
import { Route as DunyaFutboluAlmaniyaRouteImport } from './routes/dunya-futbolu/almaniya'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ArticleRouteImport } from './routes/article.'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferlerRoute = TransferlerRouteImport.update({
  id: '/transferler',
  path: '/transferler',
  getParentRoute: () => rootRouteImport,
} as any)
const ElaqeRoute = ElaqeRouteImport.update({
  id: '/elaqe',
  path: '/elaqe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const XeberlerIndexRoute = XeberlerIndexRouteImport.update({
  id: '/xeberler/',
  path: '/xeberler/',
  getParentRoute: () => rootRouteImport,
} as any)
const OlkeFutboluIndexRoute = OlkeFutboluIndexRouteImport.update({
  id: '/olke-futbolu/',
  path: '/olke-futbolu/',
  getParentRoute: () => rootRouteImport,
} as any)
const DunyaFutboluIndexRoute = DunyaFutboluIndexRouteImport.update({
  id: '/dunya-futbolu/',
  path: '/dunya-futbolu/',
  getParentRoute: () => rootRouteImport,
} as any)
const OlkeFutboluPremyerLiqaRoute = OlkeFutboluPremyerLiqaRouteImport.update({
  id: '/olke-futbolu/premyer-liqa',
  path: '/olke-futbolu/premyer-liqa',
  getParentRoute: () => rootRouteImport,
} as any)
const OlkeFutboluMilliKomandaRoute = OlkeFutboluMilliKomandaRouteImport.update({
  id: '/olke-futbolu/milli-komanda',
  path: '/olke-futbolu/milli-komanda',
  getParentRoute: () => rootRouteImport,
} as any)
const OlkeFutboluILiqaRoute = OlkeFutboluILiqaRouteImport.update({
  id: '/olke-futbolu/i-liqa',
  path: '/olke-futbolu/i-liqa',
  getParentRoute: () => rootRouteImport,
} as any)
const OlkeFutboluAzerbaycanKubokuRoute =
  OlkeFutboluAzerbaycanKubokuRouteImport.update({
    id: '/olke-futbolu/azerbaycan-kuboku',
    path: '/olke-futbolu/azerbaycan-kuboku',
    getParentRoute: () => rootRouteImport,
  } as any)
const DunyaFutboluItaliyaRoute = DunyaFutboluItaliyaRouteImport.update({
  id: '/dunya-futbolu/italiya',
  path: '/dunya-futbolu/italiya',
  getParentRoute: () => rootRouteImport,
} as any)
const DunyaFutboluIspaniyaRoute = DunyaFutboluIspaniyaRouteImport.update({
  id: '/dunya-futbolu/ispaniya',
  path: '/dunya-futbolu/ispaniya',
  getParentRoute: () => rootRouteImport,
} as any)
const DunyaFutboluIngiltereRoute = DunyaFutboluIngiltereRouteImport.update({
  id: '/dunya-futbolu/ingiltere',
  path: '/dunya-futbolu/ingiltere',
  getParentRoute: () => rootRouteImport,
} as any)
const DunyaFutboluChempionlarLiqasiRoute =
  DunyaFutboluChempionlarLiqasiRouteImport.update({
    id: '/dunya-futbolu/chempionlar-liqasi',
    path: '/dunya-futbolu/chempionlar-liqasi',
    getParentRoute: () => rootRouteImport,
  } as any)
const DunyaFutboluAlmaniyaRoute = DunyaFutboluAlmaniyaRouteImport.update({
  id: '/dunya-futbolu/almaniya',
  path: '/dunya-futbolu/almaniya',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleRoute = ArticleRouteImport.update({
  id: '/article/',
  path: '/article/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elaqe': typeof ElaqeRoute
  '/transferler': typeof TransferlerRoute
  '/video': typeof VideoRoute
  '/article/': typeof ArticleRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/dunya-futbolu/almaniya': typeof DunyaFutboluAlmaniyaRoute
  '/dunya-futbolu/chempionlar-liqasi': typeof DunyaFutboluChempionlarLiqasiRoute
  '/dunya-futbolu/ingiltere': typeof DunyaFutboluIngiltereRoute
  '/dunya-futbolu/ispaniya': typeof DunyaFutboluIspaniyaRoute
  '/dunya-futbolu/italiya': typeof DunyaFutboluItaliyaRoute
  '/olke-futbolu/azerbaycan-kuboku': typeof OlkeFutboluAzerbaycanKubokuRoute
  '/olke-futbolu/i-liqa': typeof OlkeFutboluILiqaRoute
  '/olke-futbolu/milli-komanda': typeof OlkeFutboluMilliKomandaRoute
  '/olke-futbolu/premyer-liqa': typeof OlkeFutboluPremyerLiqaRoute
  '/dunya-futbolu/': typeof DunyaFutboluIndexRoute
  '/olke-futbolu/': typeof OlkeFutboluIndexRoute
  '/xeberler/': typeof XeberlerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elaqe': typeof ElaqeRoute
  '/transferler': typeof TransferlerRoute
  '/video': typeof VideoRoute
  '/article': typeof ArticleRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/dunya-futbolu/almaniya': typeof DunyaFutboluAlmaniyaRoute
  '/dunya-futbolu/chempionlar-liqasi': typeof DunyaFutboluChempionlarLiqasiRoute
  '/dunya-futbolu/ingiltere': typeof DunyaFutboluIngiltereRoute
  '/dunya-futbolu/ispaniya': typeof DunyaFutboluIspaniyaRoute
  '/dunya-futbolu/italiya': typeof DunyaFutboluItaliyaRoute
  '/olke-futbolu/azerbaycan-kuboku': typeof OlkeFutboluAzerbaycanKubokuRoute
  '/olke-futbolu/i-liqa': typeof OlkeFutboluILiqaRoute
  '/olke-futbolu/milli-komanda': typeof OlkeFutboluMilliKomandaRoute
  '/olke-futbolu/premyer-liqa': typeof OlkeFutboluPremyerLiqaRoute
  '/dunya-futbolu': typeof DunyaFutboluIndexRoute
  '/olke-futbolu': typeof OlkeFutboluIndexRoute
  '/xeberler': typeof XeberlerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elaqe': typeof ElaqeRoute
  '/transferler': typeof TransferlerRoute
  '/video': typeof VideoRoute
  '/article/': typeof ArticleRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/dunya-futbolu/almaniya': typeof DunyaFutboluAlmaniyaRoute
  '/dunya-futbolu/chempionlar-liqasi': typeof DunyaFutboluChempionlarLiqasiRoute
  '/dunya-futbolu/ingiltere': typeof DunyaFutboluIngiltereRoute
  '/dunya-futbolu/ispaniya': typeof DunyaFutboluIspaniyaRoute
  '/dunya-futbolu/italiya': typeof DunyaFutboluItaliyaRoute
  '/olke-futbolu/azerbaycan-kuboku': typeof OlkeFutboluAzerbaycanKubokuRoute
  '/olke-futbolu/i-liqa': typeof OlkeFutboluILiqaRoute
  '/olke-futbolu/milli-komanda': typeof OlkeFutboluMilliKomandaRoute
  '/olke-futbolu/premyer-liqa': typeof OlkeFutboluPremyerLiqaRoute
  '/dunya-futbolu/': typeof DunyaFutboluIndexRoute
  '/olke-futbolu/': typeof OlkeFutboluIndexRoute
  '/xeberler/': typeof XeberlerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/elaqe'
    | '/transferler'
    | '/video'
    | '/article/'
    | '/article/$slug'
    | '/dunya-futbolu/almaniya'
    | '/dunya-futbolu/chempionlar-liqasi'
    | '/dunya-futbolu/ingiltere'
    | '/dunya-futbolu/ispaniya'
    | '/dunya-futbolu/italiya'
    | '/olke-futbolu/azerbaycan-kuboku'
    | '/olke-futbolu/i-liqa'
    | '/olke-futbolu/milli-komanda'
    | '/olke-futbolu/premyer-liqa'
    | '/dunya-futbolu/'
    | '/olke-futbolu/'
    | '/xeberler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/elaqe'
    | '/transferler'
    | '/video'
    | '/article'
    | '/article/$slug'
    | '/dunya-futbolu/almaniya'
    | '/dunya-futbolu/chempionlar-liqasi'
    | '/dunya-futbolu/ingiltere'
    | '/dunya-futbolu/ispaniya'
    | '/dunya-futbolu/italiya'
    | '/olke-futbolu/azerbaycan-kuboku'
    | '/olke-futbolu/i-liqa'
    | '/olke-futbolu/milli-komanda'
    | '/olke-futbolu/premyer-liqa'
    | '/dunya-futbolu'
    | '/olke-futbolu'
    | '/xeberler'
  id:
    | '__root__'
    | '/'
    | '/elaqe'
    | '/transferler'
    | '/video'
    | '/article/'
    | '/article/$slug'
    | '/dunya-futbolu/almaniya'
    | '/dunya-futbolu/chempionlar-liqasi'
    | '/dunya-futbolu/ingiltere'
    | '/dunya-futbolu/ispaniya'
    | '/dunya-futbolu/italiya'
    | '/olke-futbolu/azerbaycan-kuboku'
    | '/olke-futbolu/i-liqa'
    | '/olke-futbolu/milli-komanda'
    | '/olke-futbolu/premyer-liqa'
    | '/dunya-futbolu/'
    | '/olke-futbolu/'
    | '/xeberler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElaqeRoute: typeof ElaqeRoute
  TransferlerRoute: typeof TransferlerRoute
  VideoRoute: typeof VideoRoute
  ArticleRoute: typeof ArticleRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  DunyaFutboluAlmaniyaRoute: typeof DunyaFutboluAlmaniyaRoute
  DunyaFutboluChempionlarLiqasiRoute: typeof DunyaFutboluChempionlarLiqasiRoute
  DunyaFutboluIngiltereRoute: typeof DunyaFutboluIngiltereRoute
  DunyaFutboluIspaniyaRoute: typeof DunyaFutboluIspaniyaRoute
  DunyaFutboluItaliyaRoute: typeof DunyaFutboluItaliyaRoute
  OlkeFutboluAzerbaycanKubokuRoute: typeof OlkeFutboluAzerbaycanKubokuRoute
  OlkeFutboluILiqaRoute: typeof OlkeFutboluILiqaRoute
  OlkeFutboluMilliKomandaRoute: typeof OlkeFutboluMilliKomandaRoute
  OlkeFutboluPremyerLiqaRoute: typeof OlkeFutboluPremyerLiqaRoute
  DunyaFutboluIndexRoute: typeof DunyaFutboluIndexRoute
  OlkeFutboluIndexRoute: typeof OlkeFutboluIndexRoute
  XeberlerIndexRoute: typeof XeberlerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferler': {
      id: '/transferler'
      path: '/transferler'
      fullPath: '/transferler'
      preLoaderRoute: typeof TransferlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elaqe': {
      id: '/elaqe'
      path: '/elaqe'
      fullPath: '/elaqe'
      preLoaderRoute: typeof ElaqeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xeberler/': {
      id: '/xeberler/'
      path: '/xeberler'
      fullPath: '/xeberler/'
      preLoaderRoute: typeof XeberlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olke-futbolu/': {
      id: '/olke-futbolu/'
      path: '/olke-futbolu'
      fullPath: '/olke-futbolu/'
      preLoaderRoute: typeof OlkeFutboluIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dunya-futbolu/': {
      id: '/dunya-futbolu/'
      path: '/dunya-futbolu'
      fullPath: '/dunya-futbolu/'
      preLoaderRoute: typeof DunyaFutboluIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olke-futbolu/premyer-liqa': {
      id: '/olke-futbolu/premyer-liqa'
      path: '/olke-futbolu/premyer-liqa'
      fullPath: '/olke-futbolu/premyer-liqa'
      preLoaderRoute: typeof OlkeFutboluPremyerLiqaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olke-futbolu/milli-komanda': {
      id: '/olke-futbolu/milli-komanda'
      path: '/olke-futbolu/milli-komanda'
      fullPath: '/olke-futbolu/milli-komanda'
      preLoaderRoute: typeof OlkeFutboluMilliKomandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olke-futbolu/i-liqa': {
      id: '/olke-futbolu/i-liqa'
      path: '/olke-futbolu/i-liqa'
      fullPath: '/olke-futbolu/i-liqa'
      preLoaderRoute: typeof OlkeFutboluILiqaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olke-futbolu/azerbaycan-kuboku': {
      id: '/olke-futbolu/azerbaycan-kuboku'
      path: '/olke-futbolu/azerbaycan-kuboku'
      fullPath: '/olke-futbolu/azerbaycan-kuboku'
      preLoaderRoute: typeof OlkeFutboluAzerbaycanKubokuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dunya-futbolu/italiya': {
      id: '/dunya-futbolu/italiya'
      path: '/dunya-futbolu/italiya'
      fullPath: '/dunya-futbolu/italiya'
      preLoaderRoute: typeof DunyaFutboluItaliyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dunya-futbolu/ispaniya': {
      id: '/dunya-futbolu/ispaniya'
      path: '/dunya-futbolu/ispaniya'
      fullPath: '/dunya-futbolu/ispaniya'
      preLoaderRoute: typeof DunyaFutboluIspaniyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dunya-futbolu/ingiltere': {
      id: '/dunya-futbolu/ingiltere'
      path: '/dunya-futbolu/ingiltere'
      fullPath: '/dunya-futbolu/ingiltere'
      preLoaderRoute: typeof DunyaFutboluIngiltereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dunya-futbolu/chempionlar-liqasi': {
      id: '/dunya-futbolu/chempionlar-liqasi'
      path: '/dunya-futbolu/chempionlar-liqasi'
      fullPath: '/dunya-futbolu/chempionlar-liqasi'
      preLoaderRoute: typeof DunyaFutboluChempionlarLiqasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dunya-futbolu/almaniya': {
      id: '/dunya-futbolu/almaniya'
      path: '/dunya-futbolu/almaniya'
      fullPath: '/dunya-futbolu/almaniya'
      preLoaderRoute: typeof DunyaFutboluAlmaniyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/': {
      id: '/article/'
      path: '/article'
      fullPath: '/article/'
      preLoaderRoute: typeof ArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElaqeRoute: ElaqeRoute,
  TransferlerRoute: TransferlerRoute,
  VideoRoute: VideoRoute,
  ArticleRoute: ArticleRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  DunyaFutboluAlmaniyaRoute: DunyaFutboluAlmaniyaRoute,
  DunyaFutboluChempionlarLiqasiRoute: DunyaFutboluChempionlarLiqasiRoute,
  DunyaFutboluIngiltereRoute: DunyaFutboluIngiltereRoute,
  DunyaFutboluIspaniyaRoute: DunyaFutboluIspaniyaRoute,
  DunyaFutboluItaliyaRoute: DunyaFutboluItaliyaRoute,
  OlkeFutboluAzerbaycanKubokuRoute: OlkeFutboluAzerbaycanKubokuRoute,
  OlkeFutboluILiqaRoute: OlkeFutboluILiqaRoute,
  OlkeFutboluMilliKomandaRoute: OlkeFutboluMilliKomandaRoute,
  OlkeFutboluPremyerLiqaRoute: OlkeFutboluPremyerLiqaRoute,
  DunyaFutboluIndexRoute: DunyaFutboluIndexRoute,
  OlkeFutboluIndexRoute: OlkeFutboluIndexRoute,
  XeberlerIndexRoute: XeberlerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
